### ISSUE TITLE
How to convery convert the text in the image to a .txt file?

### ISSUE THREAD

**Issue by NguyenDucLamK63** [tzm-tora/Stroke-Based-Scene-Text-Erasing#1]
Hi. Can you give me the solution to convert the text in the image to a .txt file? Is there a way without the .txt file and still be able to use models? Thanks

**Comment by tzm-tora** [comment]
hi, generally, there are two ways to get the text Bboxes from an unlabeled scene text image. 
1. using the detection result of pretrained scene text detectors, such as CRAFT, DB, EAST. 
2. manually draw text Bboxes by using labeling tools (e.g. PPOCRLabel).
please note that the format of Bboxes should be quadrilateral, keeping the same with ICDAR2015.

**Comment by NguyenDucLamK63** [comment]
Can you tell me what method you used? Thanks

**Comment by tzm-tora** [comment]
we used both the methods above in our paper.

**Comment by NguyenDucLamK63** [comment]
@tzm-tora  Why can't I see the part where you convert the text in the image to the coordinates in the txt file? Is there a way without the .txt file that can delete the text in the image? Thanks

**Comment by tzm-tora** [comment]
Please check the D part of EXPERIMENT in our paper. To implement our method, text Bboxes information is a must.

**Comment by NguyenDucLamK63** [comment]
Thanks
