### ISSUE TITLE
Testing dataset

### ISSUE THREAD

**Issue by NguyenDucLamK63** [tzm-tora/Stroke-Based-Scene-Text-Erasing#2]
Why does your paper use multiple datasets for training and testing? Does it make any more sense? If I use 1 dataset for testing, will there be enough conclusions to evaluate those models? Thanks

**Comment by NguyenDucLamK63** [comment]
> Why does your paper use multiple datasets for training and testing? Does it make any more sense? If I use 1 dataset for testing, will there be enough conclusions to evaluate those models? Thanks

**Comment by tzm-tora** [comment]
We only used one synthetic dataset for training. And I cannot answer your remaining questions since they are not related to our paper and codes.

**Comment by NguyenDucLamK63** [comment]
Thanks
