### ISSUE TITLE
背景修复模块中的mask_ratio

### ISSUE THREAD

**Issue by ws-lin** [tzm-tora/Stroke-Based-Scene-Text-Erasing#3]
作者您好， 最近在阅读您项目源码的时候发现背景修复模块中有个mask_ratio，不是很理解这个参数在其中的作用

**Comment by tzm-tora** [comment]
你好，你可以去阅读一下Partial Convolutional的原论文，以详细了解一下计算机制。原论文中如下解释到mask_ratio： The scaling factor sum(1)/sum(M) applies appropriate scaling to adjust for the varying amount of valid (unmasked) inputs.
