### ISSUE TITLE
Pre-trained model for Japanese font

### ISSUE THREAD

**Issue by hiyaroy12** [tzm-tora/Stroke-Based-Scene-Text-Erasing#4]
Hi, thank you for your interesting work. I have two queries:
1) Do you have the pre-trained model for Japanese font? Is it possible to share?
2) Do you have synthetic training data using Japanese font?

Thank you.

**Comment by tzm-tora** [comment]
Hi, we don’t train our model for Japanese text erasing. And we also don’t have any synthetic data for Japanese.
We plan to opensource our generation engine  in the middle of this year. Thank you.
