### ISSUE TITLE
How many training images would get a better performance? & what is the format of your training dataset? Will you open part of the training data set?

### ISSUE THREAD

**Issue by JIaqiYang78** [tzm-tora/Stroke-Based-Scene-Text-Erasing#5]
Hi, I want to ask about the number of training data sets, how many images did you use to train this model? And there was not a pre-trained model provided at you git project, can you provide it? One more question, can this model perform better in an image with so many text lines and complex layout?

**Comment by tzm-tora** [comment]
hi, 
1.  we generated a total of one million images pairs for our model training. In my opinion, the diversity of training data is more important than the volume of training data. 
2. we did provide a pre-trained model, please check the Test section in our repository.
3. I think our model will perform well if you provide appropriate Bboxes as input, you can check the performance using our pre-trained model.

**Comment by JIaqiYang78** [comment]
> hi,
> 
> 1. we generated a total of one million images pairs for our model training. In my opinion, the diversity of training data is more important than the volume of training data.
> 2. we did provide a pre-trained model, please check the Test section in our repository.
> 3. I think our model will perform well if you provide appropriate Bboxes as input, you can check the performance using our pre-trained model.

**Comment by JIaqiYang78** [comment]
I want to ask for one more question: Did there are some Chinese characters in your training data images?And I have test the performance of your pre-trained model on the real dataset which has a lot of text bounding box, it seems there is a little blurry on the erasing text region, which performs worse than your results on the synthetic scene data. Is there any method can imporve it?

**Comment by tzm-tora** [comment]
yes, half of our generated training data is Chinese characters. And it seems that the blur is an unavoidable problem in inpainting tasks, according to the size of the hole. 
In principle, the number text bounding box will not affect the performance of our method. And I am not sure what kind of real data you are testing, so I am not sure of the way to improve.
