### ISSUE TITLE
Training dataset or code to prepare it

### ISSUE THREAD

**Issue by janzd** [tzm-tora/Stroke-Based-Scene-Text-Erasing#9]
Hello!
Is it possible for you to share the training dataset you used so that it's possible to replicate your results in the paper and compare your method with other methods using the same data for training?
If it's impossible to share the dataset itself, would it be at least possible to share the code for data preparation and describe how to create the training data?

**Comment by tzm-tora** [comment]
hi, we will release our generation program after cleaning up the code, maybe later this year. if you are interested in data generation and in a hurry to use it, you can refer to this repo: https://github.com/youdao-ai/SRNet-Datagen. Actually, the code in this repo inspired us a lot.
